#!/usr/bin/env python3
# This file is part of QOBLIB - Quantum Optimization Benchmarking Library
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
update_bkv.py — maintain each problem's best-known-value (BKV) records.

For every problem class this script replays all submissions in release-date order
and combines them with the curated reference solutions in ``NN-problem/solutions/``
to produce a single best-known value per instance.

Attribution ("awarded to the first submission where it is found"):
  * The best-known value is the best over the reference and every eligible submission.
  * Because reference solutions themselves originate from submissions, the value is
    credited to the **earliest submission (by Date) that reached it**; ties on the
    date break on submission name.
  * The curated ``reference`` is credited only when *no* submission reached that value
    (e.g. a literature result better than any submission).

When a submission strictly improves the value the reference file currently holds, its
solution file is copied into ``NN-problem/solutions/`` (as ``<instance>.bst.<ext>`` or,
when the submission asserts a proven optimum, ``<instance>.opt.<ext>``) so the folder
reflects the true best. The result is written as a table inside ``solutions/README.md``
between ``<!-- BKV:START -->`` / ``<!-- BKV:END -->`` markers (replacing any prior
hand-written table); the ``Source`` column links to the crediting submission. The table
is a pure function of the submissions and references, recomputed on every run — no
extra state file is kept in the solutions folder.

Usage:
  python misc/update_bkv.py [--root .] [--check] [--summary-file PATH] [problem ...]

  --check         Do not write; exit non-zero if records are out of date.
  --summary-file  Write a human-readable list of changes (for a commit message).
  problem         Restrict to given problem dirs (e.g. 02-labs); default: all.

Exit codes: 0 = up to date / updated; 1 = (with --check) records are stale.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from site_builder import config
from site_builder.solutions import load_reference_map
from site_builder.submissions import read_csv_submissions_folder

EPOCH = "0000-00-00"          # sorts before every real submission date
FAR_FUTURE = "9999-99-99"     # for submissions with an unparseable/blank date

# The best-known table lives inside solutions/README.md between these markers; it is
# regenerated in place on every run (a pure function of submissions + references).
BKV_START = "<!-- BKV:START (auto-generated by misc/ci/update_bkv.py — do not edit) -->"
BKV_END = "<!-- BKV:END -->"

# Which problems the generator handles, and how. Every problem class is automated;
# the format-aware objective readers live in site_builder.solutions
# (read_objective / load_reference_map), so a submission and a reference can be
# compared correctly for each solution format:
#   * 02/04/08/09  labelled objective in a comment (# Energy / # Cost / # Objective).
#   * 03-birkhoff  aggregate qbench_*.json bundles (value = k).
#   * 05-sports    per-instance .sol in size-class subdirs (# Objective value).
#   * 06-portfolio .tar.gz families (bqp/uqo), best objective per λ sub-instance.
#   * 07-independentset  nodelist / .mst files (objective = size of the set).
#   * 10-topology  diameter stored in a `c … Diameter N` comment (incl. .gph.xz).
#
#   SUPPORTED    : problems we process at all.
#   FEASIBILITY  : pure-feasibility problems (no meaningful objective) — every feasible
#                  solution meets the target, so the curated reference is kept and no
#                  file is ever copied; the table reports "feasible".
SUPPORTED = {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10"}
FEASIBILITY = {"01"}

STATUS_LABEL = {
    "optimal": "optimal",
    "best_known": "best known",
    "solved": "solved",
    "open": "open",
}


def _num(value) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    if not text or text.upper() in {"N/A", "NA"}:
        return None
    try:
        return float(text.replace(",", ""))
    except ValueError:
        return None


def _is_feasible(sub: dict) -> bool:
    """A submission counts only if it declares at least one feasible run."""
    n = _num(sub.get("n_feasible"))
    return True if n is None else n > 0


def _asserts_optimum(sub: dict, value: float) -> bool:
    """Submission claims a *proven* optimum: Optimality Bound meets the objective."""
    bound = _num(sub.get("optimality_bound"))
    return bound is not None and abs(bound - value) <= 1e-9 * max(1.0, abs(value))


def _fmt_value(value: float) -> str:
    """Render an objective compactly: integers without a trailing .0."""
    if abs(value - round(value)) < 1e-9:
        return str(int(round(value)))
    return repr(value)


def _load_reference_map(problem_dir: Path) -> dict[str, dict]:
    return load_reference_map(problem_dir)


def _find_submission_solution(problem_dir: Path, source_dir: str, instance: str) -> Path | None:
    """Locate the solution file a submission provides for ``instance``.

    Prefers a single ``<instance>_solution.<ext>``; otherwise the lowest-numbered
    ``solutions/<instance>_solution_<N>.<ext>``.
    """
    base = problem_dir / "submissions" / source_dir
    if not base.is_dir():
        return None
    singles = sorted(base.rglob(f"{instance}_solution.*"))
    singles = [p for p in singles if p.is_file() and "/solutions/" not in p.as_posix()]
    if singles:
        return singles[0]
    numbered = sorted(
        p for p in base.rglob(f"{instance}_solution_*") if p.is_file()
    )
    return numbered[0] if numbered else None


def _solution_suffix(path: Path, instance: str) -> str:
    """Return the extension chain to preserve, e.g. '.sol', '.gph.xz'."""
    name = path.name
    for prefix in (f"{instance}_solution_", f"{instance}_solution"):
        if name.startswith(prefix):
            rest = name[len(prefix):]
            # For the numbered form, drop the leading '<N>' before the first dot.
            if prefix.endswith("_") and "." in rest:
                rest = rest[rest.index("."):]
            return rest if rest.startswith(".") else "." + rest
    return path.suffix


def compute_records(problem_dir: Path, minimize: bool, feasibility: bool = False) -> dict[str, dict]:
    """Compute the best-known record for every instance of one problem by replaying all
    submissions in release-date order.

    The best-known value is the best over the curated reference and every eligible
    submission. Because reference solutions themselves originate from submissions, the
    value is credited to the **earliest submission (by Date) that reached it**; the
    curated ``reference`` is credited only when no submission reached that value (e.g.
    a literature result). When ``feasibility`` is set, objectives are ignored: the
    reference is kept and reported as "feasible".
    """
    ref_map = _load_reference_map(problem_dir)
    # Passing the real instance names lets a row whose "Problem" column is
    # non-standard (e.g. "LABS (N = 10)") fall back to the instance encoded in its
    # <instance>_summary.csv filename, instead of creating a bogus instance.
    known = set(ref_map.keys())
    subs = {} if feasibility else read_csv_submissions_folder(
        problem_dir / "submissions", known_instances=known or None)

    instances = set(ref_map) | set(subs)
    records: dict[str, dict] = {}

    def better(a: float, b: float) -> bool:
        return a < b - 1e-9 * max(1.0, abs(b)) if minimize else a > b + 1e-9 * max(1.0, abs(b))

    for inst in instances:
        ref = ref_map.get(inst)
        # Feasibility problems have no comparable objective; force the value to None so
        # the reader's best-effort number (e.g. a 0/1 string read as an integer) is
        # ignored and the reference is simply kept as "feasible".
        ref_val = None if feasibility else (_num(ref.get("value")) if ref else None)
        ref_status = (ref.get("status") if ref else None) or "best_known"

        # Eligible submissions: feasible, numeric value, with a locatable solution file
        # (a CSV-only claim cannot be awarded a best-known value). Replayed oldest-first.
        sub_cands = []
        for sub in subs.get(inst, []):
            val = _num(sub.get("value"))
            if val is None or not _is_feasible(sub):
                continue
            src_dir = sub.get("_source_dir", "")
            sol_path = _find_submission_solution(problem_dir, src_dir, inst)
            if sol_path is None:
                continue
            sub_cands.append({
                "value": val,
                "status": "optimal" if _asserts_optimum(sub, val) else "best_known",
                "source": src_dir or "?",
                "date": (sub.get("date") or "").strip(),
                "is_reference": False,
                "sub_dir": src_dir,
                "sol_path": sol_path,
                "_sort": ((sub.get("date") or "").strip() or FAR_FUTURE, src_dir),
            })
        sub_cands.sort(key=lambda c: c["_sort"])

        # Best value over the reference and all submissions.
        values = ([ref_val] if ref_val is not None else []) + [c["value"] for c in sub_cands]

        current: dict | None = None
        if feasibility or not values:
            # Feasibility (or no readable numeric value): keep the reference as the
            # baseline; if there is no reference, credit the earliest feasible submission.
            if ref is not None:
                current = {"value": None, "status": ref_status, "source": "reference",
                           "date": "", "is_reference": True, "sub_dir": None, "sol_path": None}
            elif sub_cands:
                current = dict(sub_cands[0]); current["value"] = None
        else:
            best = min(values) if minimize else max(values)
            ref_is_best = ref_val is not None and not better(best, ref_val) and not better(ref_val, best)
            at_best = [c for c in sub_cands if not better(best, c["value"]) and not better(c["value"], best)]
            if ref_is_best and ref_status == "optimal":
                # A proven-optimal (or otherwise curated/literature) reference is kept as
                # the source even if a later submission reproduced the value — it is not
                # a submission result. (A submission can never *beat* a proven optimum.)
                current = {"value": ref_val, "status": "optimal", "source": "reference",
                           "date": "", "is_reference": True, "sub_dir": None, "sol_path": None}
            elif at_best:
                # best-known frontier reached by a submission → credit the earliest one.
                current = at_best[0]
            else:
                # Only the reference reached the best value → a genuine reference result.
                current = {"value": ref_val, "status": ref_status, "source": "reference",
                           "date": "", "is_reference": True, "sub_dir": None, "sol_path": None}

        if current is None:
            continue

        # Objective problems: drop instances with no known value anywhere (no readable
        # reference objective and no submission) — they carry no best-known information.
        # Feasibility problems intentionally keep value-less "feasible" reference rows.
        if not feasibility and current.get("value") is None:
            continue

        # The on-disk solution file is (re)written only when a submission wins and it is
        # a strict numeric improvement over what the reference file currently holds (or
        # there is no reference file at all). Ties leave the existing file untouched.
        current["changed"] = not current["is_reference"] and (
            ref is None or (ref_val is not None and better(current["value"], ref_val))
        )
        current["prev_value"] = ref_val
        records[inst] = current

    return records


def apply_file_copies(
    problem_dir: Path,
    problem_id: str,
    records: dict[str, dict],
    do_write: bool,
    changes: list[str],
) -> None:
    """Copy a submission's winning solution file into solutions/ where it improves.

    Feasibility problems never reach here with a submission record (they keep the
    reference), so no extra guard is needed.
    """
    solutions_dir = problem_dir / "solutions"

    for inst, rec in sorted(records.items()):
        # Only copy a file when this run newly attributes the instance to a submission
        # (compute_records sets rec["changed"]); unchanged records are already applied.
        if not rec.get("changed") or rec["is_reference"] or not rec.get("sol_path"):
            continue
        src = rec["sol_path"]

        marker = "opt" if rec["status"] == "optimal" else "bst"
        suffix = _solution_suffix(src, inst)
        target = solutions_dir / f"{inst}.{marker}{suffix}"

        pv = rec.get("prev_value")
        pvs = "none" if pv is None else _fmt_value(pv)
        changes.append(
            f"  * {problem_dir.name}/{inst}: {pvs} -> {_fmt_value(rec['value'])} "
            f"(source: {rec['sub_dir']}); {target.name}"
        )
        if do_write:
            # Remove any stale status-marked files for this instance to avoid duplicates.
            for stale in solutions_dir.glob(f"{inst}.opt.*"):
                stale.unlink()
            for stale in solutions_dir.glob(f"{inst}.bst.*"):
                stale.unlink()
            for stale in solutions_dir.glob(f"{inst}.solved.*"):
                stale.unlink()
            shutil.copyfile(src, target)


def render_section(records: dict[str, dict], feasibility: bool = False) -> str:
    """Render the marker-delimited best-known section embedded in solutions/README.md."""
    lines = [
        BKV_START,
        "## Best-known values",
        "",
        "> Auto-generated — the best-known value for each instance and the first source",
        "> (a submission directory, or `reference` for a curated reference solution)",
        "> that reached it.",
    ]
    if feasibility:
        lines += [
            ">",
            "> ℹ️ This is a pure-feasibility problem: any feasible solution meets the",
            "> target, so the curated **reference** solutions are listed as `feasible`.",
        ]
    lines += [
        "",
        "| Instance | Best Known | Status | Source | Date |",
        "| :------- | ---------: | :----- | :----- | :--- |",
    ]
    for inst in sorted(records):
        rec = records[inst]
        status = STATUS_LABEL.get(rec["status"], rec["status"])
        if rec["is_reference"]:
            source = "reference"
        else:
            # Link to the submission directory (relative to solutions/README.md).
            source = f"[{rec['source']}](../submissions/{rec['source']})"
        date = rec["date"] or "—"
        value = "feasible" if rec["value"] is None else _fmt_value(rec["value"])
        lines.append(f"| {inst} | {value} | {status} | {source} | {date} |")
    lines += ["", BKV_END]
    return "\n".join(lines)


def _strip_markdown_tables(text: str):
    """Remove contiguous markdown-table blocks (runs of lines starting with '|'),
    returning the first removed block's line index so the new section can take its
    place. Prose and headings are kept."""
    lines = text.splitlines()
    out: list[str] = []
    first_table_at = None
    i = 0
    while i < len(lines):
        if lines[i].lstrip().startswith("|"):
            if first_table_at is None:
                # Drop the (blank lines and) heading that titled the removed table, so
                # the generated section's own heading takes its place cleanly.
                while out and out[-1].strip() == "":
                    out.pop()
                if out and out[-1].lstrip().startswith("#"):
                    out.pop()
                first_table_at = len(out)
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out), first_table_at


def write_readme_section(solutions_dir: Path, section: str, do_write: bool) -> bool:
    """Insert/replace the BKV table in solutions/README.md. Returns True if it changed.

    On the first run the hand-written table is dropped (its position is taken by the
    generated section); prose/headings are preserved. Afterwards the section between
    the BKV markers is replaced in place.
    """
    readme = solutions_dir / "README.md"
    old = readme.read_text(encoding="utf-8") if readme.exists() else None

    if old is not None and BKV_START in old and BKV_END in old:
        before = old.split(BKV_START, 1)[0].rstrip("\n")
        after = old.split(BKV_END, 1)[1].strip("\n")
        parts = [p for p in (before, section, after) if p]
        # Collapse runs of blank lines so the result is stable across re-runs
        # (any prose/headings kept after the marker must not accrete blank lines).
        new = re.sub(r"\n{3,}", "\n\n", "\n\n".join(parts)).strip("\n") + "\n"
    elif old is not None:
        stripped, table_at = _strip_markdown_tables(old)
        body = [ln for ln in stripped.splitlines()]
        if table_at is not None:
            body[table_at:table_at] = ["", section, ""]
        else:
            body += ["", section]
        new = re.sub(r"\n{3,}", "\n\n", "\n".join(body)).strip("\n") + "\n"
    else:
        new = "# Solutions\n\n" + section + "\n"

    if new == old:
        return False
    if do_write:
        readme.parent.mkdir(parents=True, exist_ok=True)
        readme.write_text(new, encoding="utf-8")
    return True


def process_problem(problem_dir: Path, do_write: bool, changes: list[str]) -> bool:
    """Return True if anything changed (or would change) for this problem."""
    problem_id = problem_dir.name.split("-", 1)[0]
    if problem_id not in SUPPORTED:
        return False  # not yet automatable — see SUPPORTED / FEASIBILITY notes above
    minimize = config.PROBLEM_META.get(problem_id, {}).get("minimize", True)
    feasibility = problem_id in FEASIBILITY
    solutions_dir = problem_dir / "solutions"

    records = compute_records(problem_dir, minimize, feasibility=feasibility)
    if not records:
        return False

    changed = False

    # 1) Copy newly-attributed submission solution files into solutions/.
    before = len(changes)
    apply_file_copies(problem_dir, problem_id, records, do_write, changes)
    if len(changes) > before:
        changed = True

    # 2) Regenerate the best-known table inside solutions/README.md. The section
    #    doubles as the persisted provenance (parsed back on the next run).
    section = render_section(records, feasibility=feasibility)
    if write_readme_section(solutions_dir, section, do_write):
        changed = True
        changes.append(f"  ~ {problem_dir.name}/solutions/README.md best-known table updated ({len(records)} instances)")

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Update best-known-value records and tables.")
    parser.add_argument("--root", type=Path, default=Path("."), help="Repository root.")
    parser.add_argument("--check", action="store_true", help="Do not write; exit 1 if records are stale.")
    parser.add_argument("--summary-file", type=Path, default=None, help="Write the change list here.")
    parser.add_argument("problems", nargs="*", help="Restrict to these problem dirs (default: all).")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    config.configure(root=root)
    do_write = not args.check

    if args.problems:
        problem_dirs = [root / p for p in args.problems]
    else:
        problem_dirs = sorted(
            d for d in root.iterdir()
            if d.is_dir() and (d / "solutions").is_dir() and d.name[:2].isdigit()
        )

    changes: list[str] = []
    any_changed = False
    for problem_dir in problem_dirs:
        if not problem_dir.is_dir():
            print(f"WARNING: {problem_dir} not found; skipping.", file=sys.stderr)
            continue
        if process_problem(problem_dir, do_write, changes):
            any_changed = True

    header = "Best-known records are up to date." if not any_changed else (
        "Best-known records would change:" if args.check else "Best-known records updated:"
    )
    print(header)
    for line in changes:
        print(line)

    if args.summary_file and changes:
        args.summary_file.write_text("\n".join(changes) + "\n", encoding="utf-8")

    if args.check and any_changed:
        print("\nRun `python misc/update_bkv.py` and commit the result.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
